### ISSUE TITLE
Script 'au run' exited without indicating that the node server was listening

### ISSUE THREAD

**Issue by roddharris** [aurelia/dotnet#4]
I just used the latest template (and it did indeed remove the Dependencies Error that I was getting previously).

I created a new directory and then did the following:

    dotnet new -i aurelia-dotnet-templates
    dotnet new aurelia -ht http2 -c sass -e none

I then went into the `ClientApp` directory and ran `npm install`.  Next, I clicked the `IIS Express` button in VS2017 to launch the app in IIS Express.  The app launches just fine and I get `Hello World`.  

I clicked the `Stop` button to stop the app.  I changed the browser from Chrome to FireFox and again clicked the `IIS Express` button.  This time, the browser displays an error page:

![image](https://user-images.githubusercontent.com/9284228/55245928-8a093f80-521a-11e9-94a7-ff32a6876b68.png)

I never had this happen in the previous version of the template.  (Incidentally, it doesn't matter if I switch back to Chrome or not -- it appears as though I get one chance to run in whatever browser and then the app will no longer run.)

So, this leaves me in a state where I can no longer run the app until I restart my machine.  After restart, I can run the app one time before getting the same thing.

**Comment by brandonseydel** [comment]
Are you sure there wasn't a previous app running?  Also you don't need to npm install ever with this template if you don't want.  It automatically does it for you if missing node_modules on run.  The CLI now has a port option that I will be able to use in the coming templates to just randomly pick a port to run Aurelia on if more than one is running rather than only trying the configuration one.  This will help this issue.

**Comment by brandonseydel** [comment]
Looks like we found a bug in the new inprocess hosting for asp.net core 2.2 where it doesn't kill child processes.  I will revert back for now and open a ticket with microsoft.

**Comment by brandonseydel** [comment]
Pushed out new release.  Thank for the find!
